import { CommonModule, DOCUMENT } from '@angular/common'
import { AfterViewInit, Component, ElementRef, HostListener, OnDestroy, OnInit, ViewChild, inject, signal } from '@angular/core'
import { Meta, Title } from '@angular/platform-browser'
import { RouterLink } from '@angular/router'
import { RevealDirective } from '../../components/reveal/reveal.directive'
import { ANNUAL_BILLING_ENABLED, ANNUAL_DISCOUNT, CONTACT_EMAIL, FAQS, PRICING_PLANS, PRODUCT_TABS, SECURITY_ITEMS, type PricingPlan, type ProductTabId } from '../../config/landing.config'

@Component({ selector: 'app-landing', imports: [CommonModule, RouterLink, RevealDirective], styleUrl: './landing.component.css', template: `
<div class="oa" [class.scrolled]="scrolled()" [style.--hero-p]="heroProgress()">
  <a class="oa-skip" href="#conteudo">Ir para o conteúdo</a>
  <header class="oa-header"><div class="oa-shell oa-header-in">
    <a class="oa-brand" routerLink="/" aria-label="OdontoApp — início"><img src="assets/logo-mark-96.png" width="36" height="36" alt=""><span>Odonto<strong>App</strong></span></a>
    <nav class="oa-nav" aria-label="Navegação principal"><a href="#produto">Produto</a><a href="#recursos">Recursos</a><a href="#como-funciona">Como funciona</a><a href="#clinicas">Para clínicas</a><a href="#planos">Planos</a></nav>
    <div class="oa-header-actions"><a routerLink="/login">Entrar</a><a class="oa-btn oa-btn-sm" routerLink="/signup">Começar gratuitamente</a></div>
    <button class="oa-menu" type="button" (click)="toggleMenu()" [attr.aria-expanded]="menuOpen()" aria-controls="oa-mobile"><span class="sr-only">Abrir menu</span><i></i><i></i></button>
  </div>@if(menuOpen()){<nav id="oa-mobile" class="oa-mobile"><a href="#produto" (click)="menuOpen.set(false)">Produto</a><a href="#recursos" (click)="menuOpen.set(false)">Recursos</a><a href="#como-funciona" (click)="menuOpen.set(false)">Como funciona</a><a href="#clinicas" (click)="menuOpen.set(false)">Para clínicas</a><a href="#planos" (click)="menuOpen.set(false)">Planos</a><a routerLink="/login">Entrar</a><a class="oa-btn" routerLink="/signup">Começar gratuitamente</a></nav>}</header>

  <main id="conteudo">
    <section class="oa-hero"><div class="oa-orbits" aria-hidden="true"><i></i><i></i><i></i></div><div class="oa-shell oa-hero-copy">
      <p class="oa-kicker"><i></i>Gestão odontológica mais simples.</p><h1>Sua clínica inteira.<br><em>Em um só lugar.</em></h1>
      <p class="oa-lead">Organize agenda, pacientes, atendimentos e financeiro sem transformar a gestão da clínica em mais um problema.</p>
      <div class="oa-actions"><a class="oa-btn oa-btn-lg" routerLink="/signup">Começar gratuitamente <span>↗</span></a><a class="oa-btn oa-btn-lg oa-btn-quiet" href="#produto">Ver como funciona <span>↓</span></a></div><small class="oa-note">7 dias grátis · Configure sua clínica em poucos minutos.</small>
    </div><div class="oa-hero-stage"><div class="oa-window oa-window-hero"><ng-container [ngTemplateOutlet]="windowBar"/><ng-container [ngTemplateOutlet]="productUi" [ngTemplateOutletContext]="{$implicit:'overview'}"/></div></div></section>

    <section class="oa-manifest"><div class="oa-shell"><p appReveal>Menos sistemas.</p><p [appReveal]="70">Menos planilhas.</p><p [appReveal]="140">Menos trabalho manual.</p><strong [appReveal]="210">Uma clínica mais simples de administrar.</strong></div></section>

    <section class="oa-story" id="produto" #story><div class="oa-shell oa-story-grid"><div class="oa-story-copy"><p class="oa-eyebrow">O produto, em movimento</p>
      @for(tab of productTabs;track tab.id;let i=$index){<article class="oa-story-step" [attr.data-view]="tab.id" [class.active]="activeProduct()===tab.id"><span>0{{i+1}}</span><h2>{{storyTitle(tab.id)}}</h2><p>{{tab.description}}</p><button type="button" (click)="activeProduct.set(tab.id)">Explorar {{tab.label.toLowerCase()}} →</button></article>}
    </div><div class="oa-story-visual"><div class="oa-window"><ng-container [ngTemplateOutlet]="windowBar"/><ng-container [ngTemplateOutlet]="productUi" [ngTemplateOutletContext]="{$implicit:activeProduct()}"/></div></div></div></section>

    <section class="oa-agenda" id="recursos"><div class="oa-shell"><header class="oa-heading" appReveal><p class="oa-eyebrow">Agenda inteligente</p><h2>Sua agenda deixou de ser uma lista de horários.</h2><span>Agora ela ajuda você a entender o dia inteiro da clínica.</span></header><div class="oa-calendar-card" appReveal>
      <header><div><b>Agenda</b><span>14–18 de setembro</span></div><nav><button>‹</button><button>Hoje</button><button>›</button><strong>+ Novo atendimento</strong></nav></header><div class="oa-calendar"><aside><i></i>@for(h of hours;track h){<i>{{h}}</i>}</aside>
      @for(day of days;track day.date;let i=$index){<div class="oa-day" [class.today]="i===2"><header><small>{{day.week}}</small><b>{{day.date}}</b></header>@for(ev of day.events;track ev.name){<article [class]="'tone-'+ev.tone" [style.--row]="ev.row"><b>{{ev.time}}</b><span>{{ev.name}}</span><small>{{ev.service}}</small></article>}</div>}<i class="oa-cursor" aria-hidden="true"></i></div>
    </div></div></section>

    <section class="oa-journey" #journey [style.--journey-p]="journeyProgress()"><div class="oa-shell oa-journey-grid"><header><p class="oa-eyebrow">Jornada do paciente</p><h2>Do primeiro contato ao próximo retorno.</h2><span>Cada etapa conversa com a seguinte. A equipe encontra contexto sem procurar em várias telas.</span></header><ol>@for(step of journeySteps;track step.title;let i=$index){<li><b>{{i+1}}</b><div><small>{{step.label}}</small><h3>{{step.title}}</h3><p>{{step.text}}</p></div></li>}<i class="oa-track"><b></b></i></ol></div></section>

    <section class="oa-bento" id="clinicas"><div class="oa-shell"><header class="oa-heading oa-heading-split" appReveal><div><p class="oa-eyebrow">Uma operação conectada</p><h2>Menos telas abertas.<br>Mais contexto para decidir.</h2></div><span>As áreas que sua equipe usa todos os dias, desenhadas para funcionar como uma só rotina.</span></header><div class="oa-bento-grid">
      <article class="oa-card oa-card-agenda" appReveal><div><small>Agenda</small><h3>O dia inteiro, sem pontos cegos.</h3><p>Horários, pacientes e status em uma visão clara para a recepção.</p></div><ng-container [ngTemplateOutlet]="miniAgenda"/></article>
      <article class="oa-card oa-card-patient" [appReveal]="70"><div><small>Pacientes</small><h3>Histórico que acompanha o cuidado.</h3></div><div class="oa-patient"><i>AR</i><b>Ana Ribeiro</b><small>Paciente desde 2024</small><p>● Consulta confirmada</p><p>● Profilaxia concluída</p><p>● Retorno em 6 meses</p></div></article>
      <article class="oa-card oa-card-team" [appReveal]="110"><div><small>Equipe</small><h3>Cada pessoa vê o que precisa.</h3></div><p class="oa-avatars"><i>AS</i><i>RM</i><i>CL</i><i>+4</i></p></article>
      <article class="oa-card oa-card-finance" [appReveal]="150"><div><small>Financeiro</small><h3>Recebimentos sem planilha paralela.</h3></div><div class="oa-chart"><b>R$ 18.240</b><span>receita no período</span><svg viewBox="0 0 400 100" preserveAspectRatio="none"><path d="M0 83C45 82 50 68 90 70S140 45 180 55S220 27 260 39S320 13 400 18"/></svg></div></article>
      <article class="oa-card oa-card-service" [appReveal]="190"><div><small>Serviços</small><h3>Procedimentos e valores organizados.</h3></div><p class="oa-service"><i></i><span>Restauração em resina</span><b>R$ 380,00</b></p></article>
    </div></div></section>

    <section class="oa-dark"><div class="oa-shell"><p class="oa-eyebrow">Para quem administra</p><h2 appReveal>A clínica cresce.<br><em>A gestão não precisa ficar mais complicada.</em></h2><div class="oa-dark-lines"><article><b>01</b><h3>Informação dispersa</h3><p>Agenda, cadastro, prontuário e cobrança passam a compartilhar o mesmo contexto.</p></article><article><b>02</b><h3>Rotina sem visibilidade</h3><p>O essencial do dia aparece antes que um problema vire urgência.</p></article><article><b>03</b><h3>Equipe dependente de memória</h3><p>Processos claros ajudam todo mundo a saber o próximo passo.</p></article></div></div></section>

    <section class="oa-how" id="como-funciona"><div class="oa-shell"><header class="oa-heading" appReveal><p class="oa-eyebrow">Comece sem complicação</p><h2>Da conta criada à clínica organizada.</h2></header><ol><li appReveal><b>01</b><div><h3>Cadastre sua clínica</h3><p>Informe os dados essenciais e crie seu acesso em poucos minutos.</p></div></li><li [appReveal]="80"><b>02</b><div><h3>Configure sua equipe</h3><p>Adicione as pessoas e defina o acesso adequado para cada função.</p></div></li><li [appReveal]="160"><b>03</b><div><h3>Organize sua rotina</h3><p>Cadastre pacientes, monte a agenda e acompanhe a operação.</p></div></li></ol></div></section>

    <section class="oa-pricing" id="planos"><div class="oa-shell"><header class="oa-heading oa-heading-center" appReveal><p class="oa-eyebrow">Planos transparentes</p><h2>Escolha o tamanho da sua operação.</h2><span>Todos os planos começam com 7 dias grátis e podem ser cancelados quando você quiser.</span></header><div class="oa-toggle"><button [class.active]="!annual()" (click)="annual.set(false)">Mensal</button><button [class.active]="annual()" (click)="annual.set(true)" [disabled]="!annualEnabled">Anual <span>economize 10%</span></button></div><div class="oa-prices">
      @for(plan of plans;track plan.code;let i=$index){<article class="oa-price" [class.featured]="plan.highlight" [appReveal]="i*70">@if(plan.highlightLabel){<em>{{plan.highlightLabel}}</em>}<header><b>{{plan.name}}</b><span>{{plan.tagline}}</span></header><p class="oa-value"><small>R$</small><strong>{{displayPrice(plan)}}</strong><span>/mês</span></p>@if(annual()){<p class="oa-annual">R$ {{annualTotal(plan)}} cobrados anualmente</p>}<h4>{{plan.limitLabel}}</h4><ul>@for(feature of plan.highlights;track feature.label){<li><i>✓</i>{{feature.label}}</li>}</ul><a class="oa-btn" routerLink="/signup" [queryParams]="{plan:plan.code,cycle:annual()?'yearly':'monthly'}">Começar gratuitamente</a></article>}
    </div></div></section>

    <section class="oa-security"><div class="oa-shell oa-security-grid"><header><p class="oa-eyebrow">Segurança por princípio</p><h2>Dados clínicos pedem cuidado em cada camada.</h2><span>Proteção faz parte da arquitetura — não é um extra.</span></header><ul>@for(item of securityItems.slice(0,4);track item.title){<li><i>✓</i><span><b>{{item.title}}</b><small>{{item.description}}</small></span></li>}</ul></div></section>

    <section class="oa-faq"><div class="oa-shell oa-faq-grid"><header><p class="oa-eyebrow">Perguntas frequentes</p><h2>O que você precisa saber antes de começar.</h2><span>Ainda ficou alguma dúvida? <a [href]="supportMailto">Fale com a nossa equipe.</a></span></header><div>@for(faq of faqs;track faq.question;let i=$index){<article [class.open]="openFaq()===i"><button (click)="toggleFaq(i)" [attr.aria-expanded]="openFaq()===i"><span>{{faq.question}}</span><i>+</i></button>@if(openFaq()===i){<p>{{faq.answer}}</p>}</article>}</div></div></section>

    <section class="oa-final"><div class="oa-shell"><p class="oa-kicker"><i></i>Comece sem complicação.</p><h2>Sua clínica merece<br>uma gestão mais simples.</h2><p>Conheça o OdontoApp por 7 dias. Sem cobrança automática durante o teste.</p><div class="oa-actions"><a class="oa-btn oa-btn-lg" routerLink="/signup">Começar gratuitamente ↗</a><a class="oa-btn oa-btn-lg oa-btn-quiet" href="#produto">Conhecer o OdontoApp</a></div></div></section>
  </main>
  <footer class="oa-footer"><div class="oa-shell"><div class="oa-footer-grid"><div><a class="oa-brand" routerLink="/"><img src="assets/logo-mark-96.png" width="42" height="42" alt=""><span>Odonto<strong>App</strong></span></a><p>Gestão odontológica mais simples.</p></div><nav><b>Produto</b><a href="#produto">Visão geral</a><a href="#recursos">Recursos</a><a href="#planos">Planos</a></nav><nav><b>Empresa</b><a [href]="supportMailto">Contato</a><a href="assets/termos-de-uso.html">Termos</a><a href="assets/politica-de-privacidade.html">Privacidade</a></nav><nav><b>Acesso</b><a routerLink="/login">Entrar</a><a routerLink="/signup">Criar conta</a></nav></div><p class="oa-footer-word">OdontoApp</p><p class="oa-footer-bottom"><span>© {{year}} OdontoApp</span><span>Desenvolvido por MoreliDev</span></p></div></footer>
</div>

<ng-template #windowBar><div class="oa-windowbar"><span><i></i><i></i><i></i></span><b>app.odontoapp.com</b><small>Seguro</small></div></ng-template>
<ng-template #miniAgenda><div class="oa-mini"><span>08:00</span><i></i><b>Ana Ribeiro</b><em>Concluído</em><span>09:30</span><i></i><b>Carlos Menezes</b><em>Confirmado</em><span>11:00</span><i></i><b>Juliana Prado</b><em>Agendado</em></div></ng-template>
<ng-template #productUi let-view><div class="oa-app"><aside><div><img src="assets/logo-mark-48.png" width="24" height="24" alt=""><b>OdontoApp</b></div><nav><i class="active"></i><i></i><i></i><i></i><i></i></nav><span>AM</span></aside><main><header><div><small>{{productEyebrow(view)}}</small><b>{{productHeading(view)}}</b></div><i></i><span>AM</span></header><section>
  @switch(view){
    @case('agenda'){<div class="oa-ui-toolbar"><b>Agenda semanal</b><span>Hoje</span><button>+ Novo agendamento</button></div><ng-container [ngTemplateOutlet]="miniAgenda"/><div class="oa-bars"><i></i><i></i><i></i><i></i><i></i></div>}
    @case('patients'){<div class="oa-ui-toolbar"><b>Pacientes</b><span>248 cadastrados</span><button>+ Novo paciente</button></div><div class="oa-patients">@for(p of [['AR','Ana Ribeiro'],['CM','Carlos Menezes'],['JP','Juliana Prado']];track p[0]){<p><i>{{p[0]}}</i><b>{{p[1]}}</b><small>(27) 99912-4580</small><em>Ativo</em></p>}</div>}
    @case('records'){<div class="oa-record-head"><i>AR</i><div><b>Ana Ribeiro</b><small>Paciente desde março de 2024</small></div><button>Nova evolução</button></div><div class="oa-record"><nav><b>Resumo</b><span>Prontuário</span><span>Odontograma</span></nav><article><small>Linha do tempo</small><h4>Profilaxia e avaliação periódica</h4><p>Procedimento concluído. Orientações registradas e retorno programado.</p></article></div>}
    @case('finance'){<ng-container [ngTemplateOutlet]="kpis"/><div class="oa-bigchart"><span>Receita</span><svg viewBox="0 0 500 120" preserveAspectRatio="none"><path d="M0 105C50 97 55 85 100 88S165 59 205 68S268 38 310 49S380 18 500 23"/></svg></div>}
    @default{<ng-container [ngTemplateOutlet]="kpis"/><div class="oa-dashboard"><div><span>Agenda de hoje</span><ng-container [ngTemplateOutlet]="miniAgenda"/></div><div><span>Visão financeira</span><svg viewBox="0 0 300 100" preserveAspectRatio="none"><path d="M0 86C40 80 50 67 84 70S130 43 170 52S220 25 300 18"/></svg></div></div>}
  }
</section></main></div></ng-template>
<ng-template #kpis><div class="oa-kpis"><article><span>Pacientes</span><b>248</b><small>+8 neste mês</small></article><article><span>Consultas hoje</span><b>12</b><small>9 confirmadas</small></article><article><span>Receita do mês</span><b>R$ 18.240</b><small>+12% no período</small></article></div></ng-template>
` })
export class LandingComponent implements OnInit, AfterViewInit, OnDestroy {
  private title=inject(Title); private meta=inject(Meta); private doc=inject(DOCUMENT); private observer?:IntersectionObserver; private raf=0; private nodes:HTMLElement[]=[]
  @ViewChild('story') story?:ElementRef<HTMLElement>; @ViewChild('journey') journey?:ElementRef<HTMLElement>
  readonly plans=PRICING_PLANS; readonly productTabs=PRODUCT_TABS; readonly securityItems=SECURITY_ITEMS; readonly faqs=FAQS.slice(0,6); readonly annualEnabled=ANNUAL_BILLING_ENABLED; readonly year=new Date().getFullYear(); readonly supportMailto=`mailto:${CONTACT_EMAIL}`
  readonly scrolled=signal(false); readonly menuOpen=signal(false); readonly annual=signal(false); readonly openFaq=signal<number|null>(0); readonly activeProduct=signal<ProductTabId>('overview'); readonly heroProgress=signal(0); readonly journeyProgress=signal(0)
  readonly hours=['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00']
  readonly days=[{week:'SEG',date:'14',events:[{row:2,time:'08:30',name:'Ana Ribeiro',service:'Profilaxia',tone:'blue'}]},{week:'TER',date:'15',events:[{row:4,time:'10:30',name:'Carlos Menezes',service:'Avaliação',tone:'mint'},{row:8,time:'14:30',name:'Laura Castro',service:'Restauração',tone:'lilac'}]},{week:'QUA',date:'16',events:[{row:3,time:'09:30',name:'Juliana Prado',service:'Retorno',tone:'blue'},{row:7,time:'13:30',name:'Marcos Lima',service:'Clareamento',tone:'amber'}]},{week:'QUI',date:'17',events:[{row:5,time:'11:30',name:'Renata Alves',service:'Consulta',tone:'mint'}]},{week:'SEX',date:'18',events:[{row:2,time:'08:30',name:'Paulo Nunes',service:'Endodontia',tone:'lilac'},{row:6,time:'12:30',name:'Bianca Rocha',service:'Avaliação',tone:'blue'}]}]
  readonly journeySteps=[{label:'Antes da consulta',title:'Agendamento',text:'Horário, profissional e procedimento conectados desde o início.'},{label:'Na recepção',title:'Chegada',text:'A equipe confirma a presença e entende rapidamente quem será atendido.'},{label:'No consultório',title:'Atendimento',text:'O dentista acessa o histórico e registra a evolução sem trocar de sistema.'},{label:'Depois do cuidado',title:'Histórico',text:'Procedimentos, observações e arquivos permanecem na ficha do paciente.'},{label:'Na saída',title:'Pagamento',text:'A cobrança nasce vinculada ao paciente e fica visível no financeiro.'},{label:'Próximo passo',title:'Retorno',text:'A próxima etapa continua com todo o contexto preservado.'}]
  @HostListener('window:scroll') onScroll(){if(this.raf)return;this.raf=requestAnimationFrame(()=>{this.raf=0;const w=this.doc.defaultView;if(!w)return;this.scrolled.set(w.scrollY>24);this.heroProgress.set(Math.min(1,Math.max(0,w.scrollY/Math.min(w.innerHeight*.72,680))));const el=this.journey?.nativeElement;if(el){const r=el.getBoundingClientRect();this.journeyProgress.set(Math.min(1,Math.max(0,(w.innerHeight*.72-r.top)/(r.height-w.innerHeight*.25))))}})}
  ngOnInit(){const pageTitle='OdontoApp | Gestão odontológica simples e completa',description='Agenda, pacientes, prontuário e financeiro em uma plataforma odontológica simples, segura e feita para a rotina da sua clínica.',origin=this.doc.location?.origin||'';this.title.setTitle(pageTitle);this.meta.updateTag({name:'description',content:description});this.meta.updateTag({property:'og:title',content:pageTitle});this.meta.updateTag({property:'og:description',content:description});this.meta.updateTag({name:'twitter:title',content:pageTitle});this.meta.updateTag({name:'twitter:description',content:description});let link=this.doc.head?.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!link&&this.doc.head){link=this.doc.createElement('link');link.rel='canonical';this.doc.head.appendChild(link)}if(link)link.href=origin;const data={'@context':'https://schema.org','@type':'SoftwareApplication',name:'OdontoApp',applicationCategory:'BusinessApplication',operatingSystem:'Web',description,url:origin,offers:this.plans.map(p=>({'@type':'Offer',name:p.name,price:(p.priceCents/100).toFixed(2),priceCurrency:'BRL'}))};const s=this.doc.createElement('script');s.type='application/ld+json';s.textContent=JSON.stringify(data);this.doc.head?.appendChild(s);this.nodes.push(s)}
  ngAfterViewInit(){const w=this.doc.defaultView;if(w&&'IntersectionObserver'in w){this.observer=new IntersectionObserver(es=>{const e=es.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];const id=e?.target.getAttribute('data-view') as ProductTabId|null;if(id)this.activeProduct.set(id)},{rootMargin:'-25% 0px -48%',threshold:[0,.25,.6]});this.story?.nativeElement.querySelectorAll('.oa-story-step').forEach(e=>this.observer?.observe(e))}this.onScroll()}
  ngOnDestroy(){this.observer?.disconnect();if(this.raf)cancelAnimationFrame(this.raf);this.nodes.forEach(n=>n.remove())}
  toggleMenu(){this.menuOpen.update(value=>!value)} toggleFaq(index:number){this.openFaq.update(value=>value===index?null:index)}
  storyTitle(id:ProductTabId){return({overview:'Sua operação, logo ao entrar.',agenda:'Veja sua semana inteira em segundos.',patients:'Todo o histórico onde você espera encontrar.',records:'O cuidado registrado, do começo ao retorno.',finance:'Saiba o que entrou e o que falta receber.'} satisfies Record<ProductTabId,string>)[id]}
  productEyebrow(id:ProductTabId){return({overview:'Visão da clínica',agenda:'Organização do dia',patients:'Relacionamento',records:'Cuidado contínuo',finance:'Controle financeiro'} satisfies Record<ProductTabId,string>)[id]}
  productHeading(id:ProductTabId){return PRODUCT_TABS.find(x=>x.id===id)?.label||'Dashboard'}
  private annualMonthly(p:PricingPlan){return Math.floor((p.priceCents*(1-ANNUAL_DISCOUNT))/10)*10} private money(v:number){return(v/100).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}
  displayPrice(p:PricingPlan){return this.money(this.annual()?this.annualMonthly(p):p.priceCents)} annualTotal(p:PricingPlan){return this.money(this.annualMonthly(p)*12)}
}
